Adding unlinking feature to biosample relationship script
enasequence/ena-content-dataflow pull request #15
Opened 2021-11-23 17:19 UTC by z-w123

Added unlinking feature to script - add '-u' flag to command to unlink samples specified in an input file, e.g.

`python test_unlinking.py -s test_sample_accs_list_3.txt -c test_credentials.json --verbose -u`

(if relationships specified in input spreadsheet do not already exist in the input file, these will be ignored)

Please also test linking and then unlinking using repeated source accessions (e.g. file below) as these do not seem to be adding/removing correctly. @M-casado 

[test_sample_accs_list_3.txt](https://github.com/enasequence/ena-content-dataflow/files/7589924/test_sample_accs_list_3.txt)

2021-11-24 11:38 UTC, M-casado requested changes
Good work, @z-w123!

A few comments that I had. I have not checked the issues you mentioned in [your comment](https://github.com/enasequence/ena-content-dataflow/pull/15#issue-1061534504), but will eventually do. 

I'm a bit in a hurry with another task, but as soon as it's finished I would love to review in depth the PR, test the tool or even contribute to your PR with my edits.

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            file_data["relationships"].pop(index) # removing nested lists using integers not strings
The way the list was created there would be no duplicates, so isn't it cleaner to use ``list.remove(new_relationship)`` to pop the first occurrence of that relationship?

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +        except: #except if ValueError thrown
I would suggest that, if we know already the exception, we catch it appropriately. 
```suggestion
        except ValueError: #except if ValueError thrown
```

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            json.dump(file_data, f, indent=1)  # Converts python dictionary back into json string
Now that I notice, there's probably a better way for this, as well as the block for unlinking: opening the file and dumping the updated JSON in each loop iteration doesn't sound very efficient.

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            json.dump(file_data, f, indent=1)  # Converts python dictionary back into json string
Same as before

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            print_v(f"-- Biosamples successfully unlinked. The following relationship has been removed: 'Source sample '{source_bs}' derived from target list:\n{df_dict[source_bs]}'")
Again this feels too verbose even for me. We could probably keep track of all status codes that are fine or not and summarize them at the end of the script in a TSV printed or something

2021-11-24 11:38 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# # print(file_data.pop(["relationships"][index])) #this removes the entire relationships node? why?
I'm not sure but just from what I remember: wasn't the relationships object a dictionary? If you pop the whole dictionary with the source as Key and all targets as Values in a list, it should remove the whole thing, right?

2021-11-26 18:29 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> -
Yep, I just reshuffled some of the code in the relationships function to support unlinking aswell. Currently this function checks if the relationship exists in the json file + creates the 'new_relationship' dictionary

2021-11-26 18:32 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +        global new_relationship
To reference it outside of the function, in the 'elif args.unlink' block, in order to remove the specified relationships, one by one from the json file

2021-11-26 18:37 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# ! TBD - Add XLSX as input
No worries! I realise Pycharm adds spaces after the '#' automatically when I uncomment and comment code, but I will retain `#!` for your comments

2021-11-26 18:39 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            sys.exit()
Right, yes. I will make the change here

2021-11-26 18:42 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# # print(file_data.pop(["relationships"][index])) #this removes the entire relationships node? why?
sorry these comments are outdated and have been removed. Left it in by accident

2021-11-30 23:18 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            file_data["relationships"].pop(index) # removing nested lists using integers not strings
Done
- [ ] use list.remove() to remove relationships

2021-12-06 12:49 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> -def add_relationships(file_data, source_bs, target_list, r_type = "derived from", node_name = "relationships"):
I changed the name as I modified the function slightly - it creates the 'new_relationship' without appending it to the rel_list. 

I moved the rest of the code here to the 'if not args.unlink' statement, so that each new_relationship is only added to rel_list if the unlinking argument is not provided.

2021-12-06 12:54 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            json.dump(file_data, f, indent=1)  # Converts python dictionary back into json string
Indeed I think you are right - I have also noticed a bit of a delay between linking and unlinking samples. That is, it takes 2/3 mins for linking changes to propagate into the json file, before you can run the script again to undo them.

For now though I think we could keep what we have, and stress-test this with our first-use case?

2021-12-06 12:56 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            print_v(f"-- Biosamples successfully unlinked. The following relationship has been removed: 'Source sample '{source_bs}' derived from target list:\n{df_dict[source_bs]}'")
This is a good idea

- [ ] Summarise output

2021-12-21 11:48 UTC, M-casado reviewed
Hi @z-w123, the new additions are fine, though I would like to modify the script a bit. Also I see some unfinished TODOs that I will try to add this time.

2021-12-21 11:48 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +            print_v(f"-- Biosamples successfully unlinked. 'Source sample '{source_bs}' derived from target list:\n{df_dict[source_bs]}' has been removed")
I think this won't render as nicely as expected, since there will be extra lines in the middle. I'll change it afterwards.

2021-12-21 11:48 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +                writer.writerow([f"-- Source biosample '{source_bs}' derived from target list: {df_dict[source_bs]}", r.status_code])
Why add the ``r.status_code`` at the end if we consistently know it will be ``200`` due to the above ``if``?

2021-12-21 11:48 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +                writer.writerow([f"-- REMOVED source biosample '{source_bs}' derived from target list: {df_dict[source_bs]}", r.status_code])
Same as above comment.

2021-12-21 11:48 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# note code below would require all output tsv's to be deleted before the script is run again
Why read the file that we expect there to check the execution of the script instead of checking a variable run within the script? That way nobody needs to be aware of the ``linked_samples.tsv`` being there beforehand or not. Specially since the ``writes`` I see are appending extra information, instead of overwriting the file. So just like you mention, if that file is there you have to manually delete it before running this script.

2021-12-21 12:48 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +        global new_relationship
Not sure yet since I'm half way through the script, but I'm pretty sure this line right here is the reason only one of the relationships was unlinked, since it's a loop within the function, hence the global ``new_relationship`` variable overwrites itself at each iteration and you end up with a single ``new_relationship``.

2021-12-21 12:50 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# ! TBD - Add XLSX as input
It also separated the has-bang of the script (from ``#!`` to ``# !``, disabling it as a so). Just to be wary of it!

2021-12-22 18:08 UTC, M-casado commented
Opened another [**PR**](https://github.com/enasequence/ena-content-dataflow/pull/17) as a continuation (for I had no authority over this branch to push changes) from my forked repo.

2022-01-11 17:33 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +# ! TBD - Add XLSX as input
ah I had not noticed that, thanks!

2022-01-11 17:37 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +                writer.writerow([f"-- Source biosample '{source_bs}' derived from target list: {df_dict[source_bs]}", r.status_code])
Sure, thought we could put either - though 200 makes sense

2022-01-11 17:48 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +        global new_relationship
Ah right I see where I made the error

2022-01-11 17:50 UTC, z-w123 commented
Closing this PR as changes in #17 have been merged

2022-01-11 17:50 UTC, closed without merging

2022-01-12 09:21 UTC, M-casado commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +                writer.writerow([f"-- Source biosample '{source_bs}' derived from target list: {df_dict[source_bs]}", r.status_code])
I meant that due to the previous ``if``, every single one of the lines in the file would have status 200, so it wouldn't be that informative, since the whole file would be populated with ``r.status_code = 200``. I don't remember now what alternative I chose, but one could either say "status200.txt" or "correct_modifications.txt"; or avoid separating relationships by ``r.status_code`` with the ``if``, and let that be recorded in that column, possibly having different values.

2022-01-12 18:48 UTC, z-w123 commented on scripts/biosamples_relationships/src/biosamples_relationships.py
> +                writer.writerow([f"-- Source biosample '{source_bs}' derived from target list: {df_dict[source_bs]}", r.status_code])
Yes, I had a similar idea to create two separate files initially, depending on status code, but was not sure on the cleanest way to write this. Though I agree that the summary file alternative you chose, listing all status codes is better