add ena->biostudies script
enasequence/ena-content-dataflow pull request #2
Opened 2021-05-20 14:29 UTC by z-w123

script to take in a project xml and create a biostudies entry. This script can link multiple projects to a single biostudies entry, and can link multiple authors (provided they are from different institutions).

Working on linking multiple authors if some are from the same institutions.

2021-05-21 10:14 UTC, carlacummins requested changes
Good start @z-w123! Couple of improvements to be made around argument handling. Can you also remove any code that has been commented out and is redundant (keep anything you still think is useful)? Thanks.

2021-05-21 10:14 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +args = parser.parse_args()
Reading arguments is usually done at the start of a script, rather than the middle. Also, it's customary to have all of your `import` calls at the top too.

2021-05-21 10:14 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +####TODO: accept project as an argument#####
I think I would just add this as another argument in the `argparse.ArgumentParser()` - `-p`, `--project` would work fine.

2021-05-21 10:14 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +import datetime
All `import`s should be at the top of the file (just under the licence)

2021-05-21 10:14 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +df.to_excel('test20May.xlsx', header=None, index=False) #pagetab file output
Add another argument to define the output file name, and when this is not defined by the user, make the default include a timestamp. This can be done like so: https://github.com/enasequence/ena-content-dataflow/blob/master/scripts/fetch_covid_projects_from_db.py#L223-L225

2021-05-21 10:14 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +parser = argparse.ArgumentParser()
Would be nice to add a description here (like this : https://github.com/enasequence/ena-content-dataflow/blob/master/scripts/fetch_covid_projects_from_db.py#L60-L62)
`argparse` will automatically add an `-h`/`--help` argument and print the description provided here, so make it like a helptext kind of thing. The link I've provided should help you to see how best to format this.

2021-05-21 10:15 UTC, carlacummins commented
Also, please rename the file to remove the `_3` - no need to let people know how many versions you've made 😉

2021-05-25 11:35 UTC, z-w123 commented on scripts/ena_project_biostudies_3.py
> +args = parser.parse_args()
> Good start @z-w123! Couple of improvements to be made around argument handling. Can you also remove any code that has been commented out and is redundant (keep anything you still think is useful)? Thanks.

Thanks for the feedback @carlacummins -  I will make the corrections. Can I keep the commented notes I have included for each section as I found them helpful - or should these be removed from the version of the code on github?

2021-05-25 12:24 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +args = parser.parse_args()
Oh yes, please keep any comments that are useful - I just meant to remove any code that is no longer needed and is commented out

2021-05-25 12:25 UTC, carlacummins commented on scripts/ena_project_biostudies_3.py
> +#        values.extend(("o" + str(u + 1), args.institution[u], "")) # this is breaking the script and giving a TypeError: list indices must be integers or slices, not str
Example - is this piece of code still important enough to keep?

2021-05-25 14:42 UTC, z-w123 commented on scripts/ena_project_biostudies_3.py
> +#        values.extend(("o" + str(u + 1), args.institution[u], "")) # this is breaking the script and giving a TypeError: list indices must be integers or slices, not str
Sure, I see what you mean. These have been removed

2021-06-01 13:43 UTC, carlacummins approved these changes

2021-06-01 13:43 UTC, carlacummins commented on scripts/ena_project_biostudies.py
> +    ena_project_biostudies.py --project PRJEB37886 --author 'Zahra Waheed' --email zahra@ebi.ac.uk --institution EBI --output_file test_May_25
You're opening yourself up to spam by including your own email here 😅  
Let's add a fake person/address. Also, we can show that the output file can be a full filepath.
```suggestion
    ena_project_biostudies.py --project PRJEB37886 --author 'Joe Bloggs' --email joe@bloggs.com --institution EBI --output_file /path/to/output_file

```

2021-06-01 13:57 UTC, ahmadazd approved these changes

2021-07-08 16:26 UTC, merged