Add datahubs dormany monitoring scripts via upload
enasequence/ena-content-dataflow pull request #21
Opened 2023-10-30 11:06 UTC by jas-mckin

dhub-main.py: connects to database using oracledb and SQLalchemy
datahubs_dormancy_report.ipynb: displays information about datahubs in markdown

2023-10-30 11:41 UTC, carlacummins requested changes
Also, I think it's a good idea to create a `scripts/datahubs/` directory - please create it and move scripts there. I will move (and rename) the script we found earlier that I wrote (once I figure out what it's for 😅)

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
This is not a good filename - please make it something more descriptive of its function

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
> +Outputs for this script have been saved at /hps/nobackup/cochrane/ena/users/jasmine/
This file will be overwritten each time the script is run - is this intentional? Shouldn't it be tagged with a date stamp to prevent this and differentiate runs?

Also, it looks like you take the `save_path` from the user (or just leave it as `""`?) rather than hard coding your path now - this should change, right?

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
> +https://colab.research.google.com/github/jas-mckin/datahubs-dormancy/blob/main/datahubs_dormancy_report.ipynb
I feel like this shouldn't be hard coded either

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
> +    body += '\n\nThe scripts for this report can be found at: https://github.com/jas-mckin/datahubs-dormancy\n\nKind Regards,\nJasmine McKinnon\njasmine@ebi.ac.uk'
Currently pointing at your fork. This should change once merged.

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
> +    #pickle_outputs(proj_list, 'proj_list.pkl', save_path)
Please clean up unused, commented-out code throughout the script

2023-10-30 11:41 UTC, carlacummins commented on scripts/dhub-main.py
> +Outputs for this script have been saved at /hps/nobackup/cochrane/ena/users/jasmine/
Actually, I can see now that there are quite a few files output by this script with hard-coded filenames. In this case, it's prob best to have the script create an output dir with a timestamp instead of timestamping each file

2023-10-31 10:20 UTC, jas-mckin commented on scripts/dhub-main.py
renamed to datahubs-check-dormancy.py

2023-10-31 10:44 UTC, jas-mckin commented on scripts/dhub-main.py
> +Outputs for this script have been saved at /hps/nobackup/cochrane/ena/users/jasmine/
now includes creating a date stamped folder

2023-11-01 13:41 UTC, jas-mckin commented on scripts/dhub-main.py
> +https://colab.research.google.com/github/jas-mckin/datahubs-dormancy/blob/main/datahubs_dormancy_report.ipynb
I have also changed the address of the ipython notebook to the version that will be added to the datahubs folder on ena-sequence instead

2023-11-09 09:21 UTC, carlacummins commented on scripts/datahubs/datahubs-check-usage.py
> +save_path = "/hps/nobackup/cochrane/ena/users/jasmine/datahubs-" + today.strftime('%Y%m%d-%H:%M')
Fine as a default, but good to allow the user to define their own output path. In it's current form, nobody but you can run the script as you're the only one with permission to write here.

2023-11-09 09:21 UTC, carlacummins commented on scripts/datahubs/datahubs-check-usage.py
> +Outputs for this script have been saved at /hps/nobackup/cochrane/ena/users/jasmine/
Is this path correct? Should use the `save_path` variable to report output location?

2023-11-09 15:17 UTC, carlacummins approved these changes

2023-11-13 10:58 UTC, merged