Database counts
enasequence/ena-content-dataflow pull request #4
Opened 2021-06-03 09:53 UTC by ahmadazd

This is the first version of the script new features will be added

2021-06-09 11:02 UTC, carlacummins requested changes
This is a really good first iteration with plenty of nicely implemented code! Some improvements that could be made here and there, but

2021-06-09 14:16 UTC, z-w123 commented on scripts/data_fetch_script.py
> +from datetime import datetime
Just to make it easier to use, it could be worth creating a 'requirements.txt' file (similar to Alexie Staffer's one for the excel-validator-tool: https://github.com/ebi-ait/covid-excel-utils/blob/main/requirements.txt ) containing the names of all the modules to be installed. I believe you can remove all the import statements from the main python script this way.

The user can then run 'pip install -r requirements.txt' to install everything in one go. 


more info here: https://stackoverflow.com/questions/9956741/how-to-install-multiple-python-packages-at-once-using-pip

2021-06-09 14:41 UTC, carlacummins commented on scripts/data_fetch_script.py
> +from datetime import datetime
Yes, making a `requirements.txt` file is a good idea, but it's really just about making it easier to install everything with the single `pip` command you outlined. You still need to keep all the `import` statements tho - this is not a replacement.

2021-06-09 15:19 UTC, z-w123 commented on scripts/data_fetch_script.py
> +from datetime import datetime
ah right, thanks for the clarifying 👍

2021-08-05 08:49 UTC, ahmadazd commented on scripts/data_fetch_script.py
> +    print('PROCESSING DATA FROM ADVANCED SEARCH...................................................................')
Has been added to the end

2021-08-05 08:49 UTC, ahmadazd commented on scripts/data_fetch_script.py
> +        command = 'esearch -db {} -query "{}[ORGN]"   | esummary   | xtract -pattern DocumentSummary -element Run@acc, Experiment@acc, UpdateDate'.format(
it has been added

2021-08-05 08:50 UTC, ahmadazd commented on scripts/data_fetch_script.py
>  print('DONE...........................................................................')
alternative version been added

2021-08-05 08:50 UTC, ahmadazd commented on scripts/data_analysis_script.py
> +def fetch_and_filter_reads(connection, output):
it has been made

2021-08-05 08:58 UTC, carlacummins approved these changes

2021-08-10 10:05 UTC, merged