now supports grouped-project DOIs
enasequence/ena-content-dataflow pull request #5
Opened 2021-07-15 11:54 UTC by z-w123

The script now supports grouped-project DOIs and an author list.

To create a grouped-project biostudies entry (assigned a single DOI) the following additional args:  **title, description, center name** should be specified. Release date is optional. See below:

python ena_project_biostudies.py **-ap** PRJEB402 PRJEB1787 **-t** 'Grouped Project entry' **-d** 'this is a grouped description' **-c** 'new center name' -a 'Zahra Waheed' 'Carla Cummins' 'Ahmad Zyoud' -e zahra@org.ac.uk -i EBI NCBI DDBJ

The first author specified in the command will be the corresponding author, and an email address should be provided.
For all other authors, only the name and institution is required.

2021-07-23 14:26 UTC, carlacummins requested changes
You seem to have accidentally pushed the same file in 2 locations - once in the root of the repo and once in the `scripts/` dir. I've only reviewed the one in the `scripts/` dir as that's the correct location. Can you please remove the other one?

Only other comment would be to remove any print statements that you were just using for debugging purposes.

Thanks

2021-07-23 14:26 UTC, carlacummins commented on scripts/ena_project_biostudies.py
> +#keys = ["Submission", "Title", "ReleaseDate", "", "Study", "Title", "Description", "Center Name", "", "Link", "Description", "Type", ""]
```suggestion
```

2021-07-23 14:26 UTC, carlacummins commented on scripts/ena_project_biostudies.py
> +    release_date = args.release_date # this would need to be converted into string format?
_Does_ it need to be converted into a string? 😉  Make comment clearer

2021-07-23 14:26 UTC, carlacummins commented on scripts/ena_project_biostudies.py
> +len_oa = len(args.author[1:])
This variable is never used anywhere
```suggestion
```

2021-07-23 14:26 UTC, carlacummins commented on scripts/ena_project_biostudies.py
> +###TODO: convert input to json format
It's more like "convert argparse options to a dictionary". This way, in the future, we could read all options from a JSON configuration file (which reads really nicely into a dictionary) rather than from the command line options.

2021-07-26 08:56 UTC, z-w123 commented on scripts/ena_project_biostudies.py
> +    ena_project_biostudies.py --project PRJEB37886 --author 'Zahra Waheed' --email zahra@ebi.ac.uk --institution EBI --output_file test_May_25
Apologies about the personal details again - I copied the command over when testing. Done and examples added.

2021-07-26 08:59 UTC, z-w123 commented on scripts/ena_project_biostudies.py
> +#if grouped project biostudies entry then required args are: -ap, -t, -d, -c, -r* (quotes are required for anything longer than 1 word)
Not for a grouped biostudies record - these are not based on any 'main' projects, as in this case the information (title, description, center name etc) is specified via arguments

2021-07-26 08:59 UTC, z-w123 commented on scripts/ena_project_biostudies.py
> +    release_date = args.release_date # this would need to be converted into string format?
Thank you - it does not, so has been removed

2021-07-29 08:32 UTC, carlacummins approved these changes
Looks great, thanks @z-w123! 😄

2021-07-29 12:52 UTC, ahmadazd approved these changes

2021-07-29 12:57 UTC, merged