Biosample linking
enasequence/ena-content-dataflow pull request #9
Opened 2021-08-23 14:35 UTC by z-w123

Updates:
- creates output directory for linked biosamples
- improved error messaging
- -prod flag (dev by default) and -s for input spreadsheet with list of accessions (can be .csv or .txt)
- lowercase script name

- also added input file: test_sample_accs_list.txt to repo

2021-08-24 16:04 UTC, carlacummins requested changes

2021-08-24 16:04 UTC, carlacummins commented on scripts/biosamples_relationships.py
> +    ega_bs = target_accs[source_accs.index(ena_bs)]
This isn't a very efficient way to do this. Internally, every time you call `.index`, python has to search through the list to match it. Whereas if you were using a loop with an index counter, you wouldn't need to do the internal search each time as you could just do:
```python
for i in range(len(df)):
    ena_bs, ega_bs = source_accs[i], target_accs[i]
```
And in fact, you do a loop very similar to this above (line 97). Consider a slight restructure to make a more efficient loop.

2021-09-07 14:49 UTC, carlacummins approved these changes
Script is good! Best to include the  instructions in `.md` format as part of this same pull request, as discussed in our meeting.

2021-09-07 14:59 UTC, z-w123 commented
Thanks @carlacummins for the prompt re-review! I'll add the .md file and merge it 👍

2021-09-08 10:48 UTC, merged